### PR TITLE
Break Module Modifiers into Global & Namespaced

### PR DESCRIPTION
**Pull request by spaceninja**
(Porting this discussion over from the Google Doc, since it'll be easier to have here.)

Clarifies the two types of module modifiers we use: Global (could be applied to any module) and Namespaced (only applicable to the module they're named after).

### CODE REVIEW

**Comment by spaceninja** [comment]
@smithschwartz said:

> I'm still not a huge fan of this naming convention in general, tbh.

@spaceninja said:

> In the CMS virtually all the modifiers are scoped to a module, which is reflected in the name. To my mind, that's valuable information, letting devs know that this modifier won't be relevant except in the context of this module. I think removing the module name from a modifier that only works with a module makes the code less clear. Thoughts?

@smithschwartz said:

> I get it, and I agree with how it works. We're coming down to nitty gritty style points here. My point is that it's redundant and verbose, which leads to code that's harder to read. When you have repetition in the `.m-brand-engagement` vs. `.mm-brand-engagement` prefix, it's confusing, repetitive and easy to make a typo. In my mind, modules and modifiers are different enough to have separate prefixes that are easily scannable.

@spaceninja said:

> Fantastic! I was worried we were disagreeing about the very concept of global vs scoped. So the discussion we need to have is simply one of naming convention.

> Is there a prefix that would work better for you?

> Also, do you see a difference between global module modifiers and what I've been calling helper classes in the CMS?

> Perhaps we could standardize on `.mm-` prefix for scoped modifier and `.h-` prefix for global?

> To be clear, I'm not particularly invested in any naming convention as long as the system we land on has a distinction between global and scoped modifier, regardless of what we call them.

**Comment by spaceninja** [comment]
Okay, we're back in the new year, let's finish this discussion.

@osahan and I see a clear need for modifiers that are scoped to a particular module, distinct from modifiers that are more global.

I hear @smithschwartz's concern that the `.mm-module--modifier` convention can be confusing.

Given that we need scoped modifiers, is there a better naming solution?

Personally, I'd in favor of changing to `.h-modifier` for global modifiers and reserving `.mm-module--modifier` for scoped modifiers.

Thoughts?

**Comment by spaceninja** [comment]
Actually, I just realized I haven't been doing a good job of explaining my objection to the `.mm-modifier` (with no namespacing) approach:

If I use `.mm-inverted` as my modifier, there's nothing preventing that class from colliding with an identical modifier on an unrelated module. We end up with styles from module A impacting module B, which is bad.

We can avoid that by nesting the modifiers inside the module selector, but then we're violating Harry Roberts' rules about [not nesting](http://cssguidelin.es/#nesting) to keep your specificity tree shallow.

But we can solve both problems by namespacing the class. `.mm-module--modifier` avoids collisions and also lets me keep my modifier un-nested.

@smithschwartz  has said prefixing the modifier with the module name is redundant and verbose, but I don't agree. We already know how to read `.m-module` and `.m-module--element`, I think the "`mm`" on `.mm-module--modifier` is visually distinct enough to avoid confusion.

BEM solves this problem by using underscores for child elements and hyphens for modifiers. Last year when we discussed this, we talked about using an underscore to further visually distinguish modifiers from elements, like so: `.mm-module_modifier`

I'm not married to any particular naming convention, but I think the `.mm-modifier` approach has two serious problems (collisions and nesting) that I would like to address with namespacing, regardless of what prefix or syntax we use for it.

Sorry for writing a dictionary — I was lying on the couch thinking about this and realized I wouldn't be able to sleep until I got this down.

Thanks for reading and for your own thoughtful replies.

**Comment by doingweb** [comment]
The `mm-` prefix actually makes me feel a little weird. Most of the literature around naming conventions for this type of thing [encodes that information later on](http://csswizardry.com/2013/01/mindbemding-getting-your-head-round-bem-syntax/) (e.g., `.m-module__subcomponent`, `.m-module--modifier`). I could understand an argument around saving us from having to do regex searches all the time, but at the same time I value the idea of maintaining a hierarchy of information from left to right.

If we do want to keep `mm-` (and I'd totally understand that), I do think it should mean one thing. I intuit "module modifier" to mean "a modifier for a given module", so I'd favor it having the *namespaced* purpose, and having a different prefix for the global ones. `h-` sounds reasonable, given that it already has that purpose in another codebase of ours, though I'd like to hear more thoughts on that from others.

**Comment by thrashr888** [comment]
Just wanted to jump in with a thought that I might be way off with; might it be useful to restrict the vocabulary for the `mm-` classes? For example, a short list of allowed verbs for the property modified like `mm-is-property`, `mm-has-property`, `mm-restricts-property`, etc. That might make it less confusing to use since you can point back to the list and get more of a sense of what they do.

**Comment by waylon999** [comment]
Any more discussion to have on this or are we ready to merge it in? I think it's time to take a vote here instead of letting this rot without any more updates.

Shall we say that a no vote by Friday counts as a "yes, go for it?" ;)

**Comment by spaceninja** [comment]
I assume you meant "if you don't vote, that counts as yes" and not "if you vote no, I'll count it as a yes anyway" LOL

Either way, I vote "yes"

**Comment by thrashr888** [comment]
Any response for Chris' or my comment?

**Comment by spaceninja** [comment]
I didn't see a question in Chris', it sounded like he was in favor of the proposed change?

And I'm sorry, I thought I did reply to yours Paul, but I see I didn't. Let me do that now:

The idea of a restricted vocabulary is interesting. It overlaps a bit with the idea of state classes, which are supposed to be prefixed with .has- or .is- or something similar.

I'm not opposed to the idea, but I'm not clear on what concepts we'd limit it to — modifiers can do a wide variety of things, so my gut reaction is that a restricted vocabulary list would pretty quickly cause us to run up against the limits.

For example: what's the shared vocabulary or concept between .mm-inverted, .mm-has-svg, and .mm-button-large ?

**Comment by waylon999** [comment]
+1 from me. Final vote tally: 1-0.

**Comment by waylon999** [comment]
But in all seriousness, it's important  that we not let things rot in review like this. So we'll have to use this method, of eventually having a time limit on things, or someone has to raise a serious objection.

**Comment by spaceninja** [comment]
Cool. Closing and merging. And of course, anyone is welcome to open additional pull requests if you have ideas on how to improve our code standards.

**Review by osahan — APPROVED** [review]
+1

**Pull request merged**
